### ISSUE TITLE
Compile a 64-bit version

### ISSUE THREAD

**Issue by virtuald** [virtuald/npp_tabs#1]
A few people have asked, I just need to find a 64-bit compiler and a Windows machine somewhere.

**Comment by sjohannes** [comment]
Here's an appveyor.yml that builds both. Trying to use the old project file on newer Visual Studio was annoying, so this calls the compiler (cl.exe) directly.

Or feel free to just grab the dll from https://ci.appveyor.com/project/sjohannes/npp-tabs (I've tested and it works).

```yaml
version: '{branch}-{build}'

image: Visual Studio 2017

build_script:
- cmd: |
    set VCVARSALL="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"
    set RUN_CL=cl /LD /GL /O2 /DUNICODE /D_UNICODE *.cpp user32.lib

    %VCVARSALL% amd64
    mkdir amd64
    %RUN_CL% /Fe:amd64\npp_tabs.dll

    %VCVARSALL% amd64_x86
    mkdir x86
    %RUN_CL% /Fe:x86\npp_tabs.dll

artifacts:
- path: x86\npp_tabs.dll
- path: amd64\npp_tabs.dll
```

**Comment by virtuald** [comment]
Thanks, published to the git repo. I don't anticipate this repo receiving many changes, so I'm not going to add appveyor for now, but if I do then I'll just take this.
